// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkX2WmFgrtlTk1LlVjuUSh70LSAJxNGkw',
    appId: '1:622582943315:web:9dc7191f17126a9b1c40a6',
    messagingSenderId: '622582943315',
    projectId: 'onmywayapp-1a353',
    authDomain: 'onmywayapp-1a353.firebaseapp.com',
    storageBucket: 'onmywayapp-1a353.appspot.com',
    measurementId: 'G-9N7WMBVXC8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj3b89APjLCKtslY-xfav4v8pTaBS6g9s',
    appId: '1:622582943315:android:20d983f18e441d7c1c40a6',
    messagingSenderId: '622582943315',
    projectId: 'onmywayapp-1a353',
    storageBucket: 'onmywayapp-1a353.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGtcGKoYJJfcc-BSotq_XLmXbuZEg9-oo',
    appId: '1:622582943315:ios:18b7ba2b56947ed91c40a6',
    messagingSenderId: '622582943315',
    projectId: 'onmywayapp-1a353',
    storageBucket: 'onmywayapp-1a353.appspot.com',
    iosBundleId: 'com.example.onMyWay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGtcGKoYJJfcc-BSotq_XLmXbuZEg9-oo',
    appId: '1:622582943315:ios:833c87c41a69cf271c40a6',
    messagingSenderId: '622582943315',
    projectId: 'onmywayapp-1a353',
    storageBucket: 'onmywayapp-1a353.appspot.com',
    iosBundleId: 'com.example.onMyWay.RunnerTests',
  );
}
